name: shopab-py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - ipykernel
  - pip
  - pip:
      - pingouin
      - plotly
